[package]
name = "messagepack-core"
version = "0.1.0"
edition = "2024"

[dependencies]
num-traits = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }

[features]
default = []
std = []
