comment:                  
  layout: "condensed_header, condensed_files, condensed_footer"
  behavior: default
  require_changes: false  
  require_base: false
  require_head: true
  hide_project_coverage: false # [true :: only show coverage on the git diff aka patch coverage]

ignore:
  - "messagepack-bench"

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true