[package]
name = "messagepack-serde"
version = "0.1.0"
edition = "2024"

[dependencies]
messagepack-core = { workspace = true }
serde = { version = "1.0", default-features = false, features = ["derive"] }
num-traits = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
serde_bytes = { version = "0.11" }

[features]
default = []
std = ["serde/std", "messagepack-core/std"]
